PROJECT_NAME/Models/Bill.cs
using System.Runtime.Serialization;
using Microsoft.AspNetCore.SignalR;
namespace PROJECT_NAME.Models
{
    public class Bill
    {
     public int Quantity {get; set;}
     public double UnitPrice {get; set;}
     public double TotalAmount {get; set;}
    }
}

PROJECT_NAME/Controllers/BillController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using  PROJECT_NAME.Models;
namespace PROJECT_NAME.Controllers
{
    public class BillController : Controller
    { 
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Bill model)
        {
             if (ModelState.IsValid)
            {
                model.TotalAmount = model.Quantity * model.UnitPrice;

                ViewBag.TotalAmount = model.TotalAmount;
                ViewBag.Message = "Hoá đơn đã được tính toán thành công!";

                return View(model); 
            }

            ViewBag.Message = "Vui lòng nhập thông tin hợp lệ!";
            return View();
        }
    }
}

PROJECT_NAME/Views/Bill/Index.cshtml
@model PROJECT_NAME.Models.Bill

@{
    ViewData["Title"] = "Tính tiền hoá đơn dựa trên số lượng và đơn giá";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Index" asp-controller="Bill" method="post">
    <div>
        <label for="Quantity">Số lượng:</label>
        @Html.TextBoxFor(m => m.Quantity, new { type = "number", required = true, min = "1" })
    </div>
    <div>
        <label for="UnitPrice">Đơn giá:</label>
        @Html.TextBoxFor(m => m.UnitPrice, new { type = "number", required = true, min = "0" })
    </div>
    <button type="submit">Tính Tiền</button>
</form>

@if (ViewBag.TotalAmount != null)
{
    <h3>Tiền hoá đơn: @ViewBag.TotalAmount</h3>
    <h3>@ViewBag.Message</h3>
}